name: Deploy to Salesforce

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Salesforce DX
      uses: sfdx-actions/setup-sfdx@v1

    - name: Authorize Org
      run: sfdx auth:jwt:grant -i ${{ secrets.SALESFORCE_CONSUMER_KEY }} -f ${{ secrets.SERVER_KEY }} --username ${{ secrets.SALESFORCE_USERNAME }} -r https://login.salesforce.com

    - name: Deploy to Salesforce
      run: sfdx force:source:deploy -p force-app
