name: Deploy to Salesforce

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Salesforce DX
      uses: sfdx-actions/setup-sfdx@v1

    - name: Authorize Org
      run: |
        echo "${{ secrets.SERVER_KEY }}" > server.key
        sf auth jwt grant -o huan@daotrong.com -f server.key -i 3MVG95mg0lk4bathnRmPKo9JXuOCfrzAgjSS_rOd78cFEeKTWmqmL3bv4oGVhr9rqQxZZk.OrgCZA7C0iyr3e -r https://login.salesforce.com

    - name: Deploy to Salesforce
      run: sf project deploy start --metadata ApexClass:SpaController -o huan@daotrong.com
